####
# Playing around with F#
####

PROJECT=App
# RUNTIME=linux-x64
# FRAMEWORK=net5.0
# CONFIG=Release
# BIN?=bin


HASH = $(shell git log --pretty=format:'%h' -n 1)

usage:
	@echo "Hello! Cat the Makefile."

run:
	dotnet run --project $(PROJECT)
